name: "Run"

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC daily

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate random runs count
        id: random
        run: |
          COUNT=$(( RANDOM % 5 + 1 ))
          echo "COUNT=$COUNT" >> $GITHUB_ENV
          echo "Generated COUNT: $COUNT"

      - name: Debug COUNT
        run: echo "COUNT is $COUNT"

      - name: Loop Execution
        run: |
          for i in $(seq 1 $COUNT); do
            echo "Run #$i of $COUNT"
            sleep $(( RANDOM % 60 ))  # Random sleep between 0-60 seconds
          done

      - name: Configure Git
        run: |
          git config --global user.email "zeeshan54khan@gmail.com"
          git config --global user.name "Zeeshan"

      - name: Commit & Push changes
        run: |
          git add .
          git commit -m "Auto Commit" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
