name: "Auto Commit Workflow - Testable"

on:
  workflow_dispatch:  # You can still run it manually
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate random commit count (5–15)
        id: random
        run: |
          COUNT=$(( RANDOM % 11 + 5 ))  # 5 to 15
          echo "COUNT=$COUNT" >> $GITHUB_ENV
          echo "Will commit $COUNT times today."

      - name: Configure Git
        run: |
          git config --global user.email "zeeshan54khan@gmail.com"
          git config --global user.name "Zeeshan"

      - name: Create/Update timestamp file and Commit
        run: |
          for i in $(seq 1 $COUNT); do
            echo "Commit #$i at $(date -u)" >> timestamp.txt
            git add timestamp.txt
            git commit -m "Auto Commit #$i at $(date -u)" || echo "No changes"
            sleep $(( RANDOM % 10 + 1 ))  # 1–10 sec pause between commits
          done

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
