name: "Auto Commit Workflow - Testable"

on:
  workflow_dispatch:

permissions:
  contents: write  # ✅ Needed for push to work

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate random count (1–2)
        id: random
        run: |
          COUNT=$(( RANDOM % 2 + 1 ))
          echo "COUNT=$COUNT" >> $GITHUB_ENV
          echo "Generated COUNT: $COUNT"

      - name: Configure Git
        run: |
          git config --global user.email "zeeshan54khan@gmail.com"
          git config --global user.name "Zeeshan"

      - name: Create/Update timestamp file
        run: |
          for i in $(seq 1 $COUNT); do
            echo "Run $i at $(date -u)" >> timestamp.txt
            git add timestamp.txt
            git commit -m "Auto Commit $i at $(date -u)" || echo "Nothing to commit"
            sleep 2
          done

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
