name: "Auto Commit Workflow - Testable"

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate random runs count (1 or 2)
        id: random
        run: |
          COUNT=$(( RANDOM % 2 + 1 ))
          echo "COUNT=$COUNT" >> $GITHUB_ENV
          echo "Generated COUNT: $COUNT"

      - name: Configure Git
        run: |
          git config --global user.email "zeeshan54khan@gmail.com"
          git config --global user.name "Zeeshan"

      - name: Make and commit changes
        run: |
          for i in $(seq 1 $COUNT); do
            echo "Run #$i of $COUNT"
            echo "Commit #$i at $(date -u)" >> timestamp.txt
            git add timestamp.txt
            git commit -m "Auto Commit #$i on $(date -u)"
            sleep $(( RANDOM % 5 ))  # Short sleep for demo
          done
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
